2024-09-07 10:45:47,337 - ERROR - Validation error at index 752: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: KBTI7FI7Y3', 'input': 'KBTI7FI7Y3', 'ctx': {'error': ValueError('Invalid date format: KBTI7FI7Y3')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': '3Q791B3VIY', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'VSM4IZ4EL3', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: JJ2PDVNPRO', 'input': 'JJ2PDVNPRO', 'ctx': {'error': ValueError('Invalid date format: JJ2PDVNPRO')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `W` at 1', 'input': 'W43MSCMQ88', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `W` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:47,400 - ERROR - Validation error at index 867: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:47,466 - ERROR - Validation error at index 1023: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:47,476 - ERROR - Validation error at index 1047: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: OFH8YGZJWN', 'input': 'OFH8YGZJWN', 'ctx': {'error': ValueError('Invalid date format: OFH8YGZJWN')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': '7HSZB429UK', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'QVUW9JSKY3', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: AHN6EKASH3', 'input': 'AHN6EKASH3', 'ctx': {'error': ValueError('Invalid date format: AHN6EKASH3')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `U` at 2', 'input': 'BUE34OU973', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `U` at 2'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:47,798 - ERROR - Validation error at index 1807: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:47,957 - ERROR - Validation error at index 2103: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:48,213 - ERROR - Validation error at index 2439: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:48,341 - ERROR - Validation error at index 6526: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:48,352 - ERROR - Validation error at index 2764: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:48,449 - ERROR - Validation error at index 2997: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: PQPEUO937L', 'input': 'PQPEUO937L', 'ctx': {'error': ValueError('Invalid date format: PQPEUO937L')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'O5Q6D7FDAF', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': '0CU6LW3NKB', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: FYF2FAPZF3', 'input': 'FYF2FAPZF3', 'ctx': {'error': ValueError('Invalid date format: FYF2FAPZF3')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `U` at 3', 'input': '56URKLG01W', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `U` at 3'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:48,646 - ERROR - Validation error at index 3539: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: 7KGJ3C5TSW', 'input': '7KGJ3C5TSW', 'ctx': {'error': ValueError('Invalid date format: 7KGJ3C5TSW')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'BYU3R2LQF8', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'PG8MOC0UZI', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: QH6Z9ZPX37', 'input': 'QH6Z9ZPX37', 'ctx': {'error': ValueError('Invalid date format: QH6Z9ZPX37')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `W` at 3', 'input': 'A1W2TVMK1S', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `W` at 3'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:49,156 - ERROR - Validation error at index 4987: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:49,269 - ERROR - Validation error at index 5309: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: RQTF5XSXP4', 'input': 'RQTF5XSXP4', 'ctx': {'error': ValueError('Invalid date format: RQTF5XSXP4')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': '789HWCYC7M', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NTCGYW8LVC', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: LYVWXBBI6F', 'input': 'LYVWXBBI6F', 'ctx': {'error': ValueError('Invalid date format: LYVWXBBI6F')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `L` at 1', 'input': 'LNRNI6X6VL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `L` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:49,270 - ERROR - Validation error at index 5310: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:49,665 - ERROR - Validation error at index 6426: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: D2OZZHWOLK', 'input': 'D2OZZHWOLK', 'ctx': {'error': ValueError('Invalid date format: D2OZZHWOLK')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'TFEA83AAHP', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'FB13AKRI21', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: DM4Q84QZ03', 'input': 'DM4Q84QZ03', 'ctx': {'error': ValueError('Invalid date format: DM4Q84QZ03')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `W` at 3', 'input': '23WTQ63AET', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `W` at 3'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:49,842 - ERROR - Validation error at index 6927: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:50,134 - ERROR - Validation error at index 7747: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:50,370 - ERROR - Validation error at index 8398: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: QTVEU5TR8H', 'input': 'QTVEU5TR8H', 'ctx': {'error': ValueError('Invalid date format: QTVEU5TR8H')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'JK2J6N4DLG', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'OS2P9CMHR6', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: DOKMYDVV6L', 'input': 'DOKMYDVV6L', 'ctx': {'error': ValueError('Invalid date format: DOKMYDVV6L')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `X` at 5', 'input': '8FB8XB78NQ', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `X` at 5'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:50,599 - ERROR - Validation error at index 9026: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: L3E8OV4UAC', 'input': 'L3E8OV4UAC', 'ctx': {'error': ValueError('Invalid date format: L3E8OV4UAC')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'EIV7XWUJ8I', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': '5D74J6FPFJ', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: YBUYH8T6OE', 'input': 'YBUYH8T6OE', 'ctx': {'error': ValueError('Invalid date format: YBUYH8T6OE')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `H` at 1', 'input': 'HEGG0N3ICG', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `H` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:50,958 - ERROR - Validation error at index 10025: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,030 - ERROR - Validation error at index 10224: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: TLSTUEIKI0', 'input': 'TLSTUEIKI0', 'ctx': {'error': ValueError('Invalid date format: TLSTUEIKI0')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': '1WNILGM5MK', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'LZGTB0T5Z7', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: SRH5SM36LH', 'input': 'SRH5SM36LH', 'ctx': {'error': ValueError('Invalid date format: SRH5SM36LH')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `K` at 2', 'input': 'AKXDQ62K1V', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `K` at 2'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,035 - ERROR - Validation error at index 10237: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,086 - ERROR - Validation error at index 10373: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: YTC82GP4XE', 'input': 'YTC82GP4XE', 'ctx': {'error': ValueError('Invalid date format: YTC82GP4XE')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'U1AZKY6URZ', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'IM8MN1L9MJ', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: 4JIOCHZY0W', 'input': '4JIOCHZY0W', 'ctx': {'error': ValueError('Invalid date format: 4JIOCHZY0W')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `J` at 2', 'input': '7JTCX4UVLK', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `J` at 2'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,313 - ERROR - Validation error at index 11002: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,449 - ERROR - Validation error at index 11381: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: O1LIA1MT1N', 'input': 'O1LIA1MT1N', 'ctx': {'error': ValueError('Invalid date format: O1LIA1MT1N')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'XASHXWHN80', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'RVRFD92E48', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: 3CUODA3HTC', 'input': '3CUODA3HTC', 'ctx': {'error': ValueError('Invalid date format: 3CUODA3HTC')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 3', 'input': 'C7N3K5VF9U', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 3'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,477 - ERROR - Validation error at index 11459: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,536 - ERROR - Validation error at index 11615: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,597 - ERROR - Validation error at index 11778: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,634 - ERROR - Validation error at index 11881: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,742 - ERROR - Validation error at index 12110: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,774 - ERROR - Validation error at index 12197: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: RQI3KQXFBQ', 'input': 'RQI3KQXFBQ', 'ctx': {'error': ValueError('Invalid date format: RQI3KQXFBQ')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'YM2YGPR8W1', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'XKI9UXSCZ1', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: 8BAER2328P', 'input': '8BAER2328P', 'ctx': {'error': ValueError('Invalid date format: 8BAER2328P')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `Y` at 1', 'input': 'YIBFXQLD4A', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `Y` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:51,919 - ERROR - Validation error at index 12606: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:52,112 - ERROR - Validation error at index 13135: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: 1IA43NTJFB', 'input': '1IA43NTJFB', 'ctx': {'error': ValueError('Invalid date format: 1IA43NTJFB')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'M5ZDMLPP45', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'QREF9WLI2A', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: U9CRKSTONU', 'input': 'U9CRKSTONU', 'ctx': {'error': ValueError('Invalid date format: U9CRKSTONU')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `I` at 3', 'input': '55II6WK8D2', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `I` at 3'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:52,382 - ERROR - Validation error at index 13879: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'NULL', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1', 'input': 'NULL', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `N` at 1'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:52,472 - ERROR - Validation error at index 14124: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: M7HZECVQVC', 'input': 'M7HZECVQVC', 'ctx': {'error': ValueError('Invalid date format: M7HZECVQVC')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': 'X29OBIYMTI', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'XPVCZE2L8B', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: 9YLGYDEZNV', 'input': '9YLGYDEZNV', 'ctx': {'error': ValueError('Invalid date format: 9YLGYDEZNV')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `Y` at 2', 'input': '1YOGCW4V46', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `Y` at 2'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:45:52,616 - ERROR - Validation error at index 14523: [{'type': 'value_error', 'loc': ('date_of_birth',), 'msg': 'Value error, Invalid date format: 6WAQ2SVK0Q', 'input': '6WAQ2SVK0Q', 'ctx': {'error': ValueError('Invalid date format: 6WAQ2SVK0Q')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('email_address',), 'msg': 'value is not a valid email address: An email address must have an @-sign.', 'input': '6VIJ9KJU8P', 'ctx': {'reason': 'An email address must have an @-sign.'}}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': '44YAIDY048', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}, {'type': 'value_error', 'loc': ('join_date',), 'msg': 'Value error, Invalid date format: 7PF0SMLXII', 'input': '7PF0SMLXII', 'ctx': {'error': ValueError('Invalid date format: 7PF0SMLXII')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'uuid_parsing', 'loc': ('user_uuid',), 'msg': 'Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `P` at 2', 'input': '7PYPXC0PPN', 'ctx': {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `P` at 2'}, 'url': 'https://errors.pydantic.dev/2.8/v/uuid_parsing'}]
2024-09-07 10:46:03,024 - ERROR - Validation error at index 377: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,096 - ERROR - Validation error at index 827: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NWS3P2W38H', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: GTC9KBWJO9', 'input': 'GTC9KBWJO9', 'ctx': {'error': ValueError('Invalid date format: GTC9KBWJO9')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,099 - ERROR - Validation error at index 847: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,106 - ERROR - Validation error at index 884: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,197 - ERROR - Validation error at index 1443: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': '8YJ3TYH6Z5', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: DJIXF1AFAZ', 'input': 'DJIXF1AFAZ', 'ctx': {'error': ValueError('Invalid date format: DJIXF1AFAZ')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,350 - ERROR - Validation error at index 2418: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,362 - ERROR - Validation error at index 2489: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,415 - ERROR - Validation error at index 2830: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,552 - ERROR - Validation error at index 3694: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'ACT9K6ECRJ', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: H2PCQP4W50', 'input': 'H2PCQP4W50', 'ctx': {'error': ValueError('Invalid date format: H2PCQP4W50')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,629 - ERROR - Validation error at index 4196: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,631 - ERROR - Validation error at index 4208: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'WDWMN9TU45', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: XTD27ANR5Q', 'input': 'XTD27ANR5Q', 'ctx': {'error': ValueError('Invalid date format: XTD27ANR5Q')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,740 - ERROR - Validation error at index 4916: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'VNLNMWPJII', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: 7VGB4DA1WI', 'input': '7VGB4DA1WI', 'ctx': {'error': ValueError('Invalid date format: 7VGB4DA1WI')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,861 - ERROR - Validation error at index 5686: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:03,917 - ERROR - Validation error at index 6024: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,013 - ERROR - Validation error at index 6653: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': '4FI5GTUVYG', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: RLQYRRYHPU', 'input': 'RLQYRRYHPU', 'ctx': {'error': ValueError('Invalid date format: RLQYRRYHPU')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,117 - ERROR - Validation error at index 7332: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'RF1ACW165R', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: T008RE1ZR6', 'input': 'T008RE1ZR6', 'ctx': {'error': ValueError('Invalid date format: T008RE1ZR6')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,142 - ERROR - Validation error at index 7493: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': '6JJKS7R0WA', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: 7FL8EU9GBF', 'input': '7FL8EU9GBF', 'ctx': {'error': ValueError('Invalid date format: 7FL8EU9GBF')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,193 - ERROR - Validation error at index 7818: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'XRPE6C4GS9', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: GD9PHJXQR4', 'input': 'GD9PHJXQR4', 'ctx': {'error': ValueError('Invalid date format: GD9PHJXQR4')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,604 - ERROR - Validation error at index 10457: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': '5VN8HOLMVE', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: WCK463ZO1Z', 'input': 'WCK463ZO1Z', 'ctx': {'error': ValueError('Invalid date format: WCK463ZO1Z')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,745 - ERROR - Validation error at index 11345: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'Q7VGWP7LH9', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: OE3KONN2V6', 'input': 'OE3KONN2V6', 'ctx': {'error': ValueError('Invalid date format: OE3KONN2V6')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,765 - ERROR - Validation error at index 11465: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'ZBGGFGY4H0', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: T995FX2C7W', 'input': 'T995FX2C7W', 'ctx': {'error': ValueError('Invalid date format: T995FX2C7W')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,770 - ERROR - Validation error at index 11499: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'UMR9FIE22M', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: EVVMMB3QYV', 'input': 'EVVMMB3QYV', 'ctx': {'error': ValueError('Invalid date format: EVVMMB3QYV')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:04,987 - ERROR - Validation error at index 12876: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:05,115 - ERROR - Validation error at index 13708: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:05,303 - ERROR - Validation error at index 14884: [{'type': 'value_error', 'loc': ('expiry_date',), 'msg': 'Value error, Invalid expiry date format. Expected MM/YY.', 'input': '2ANT8LW3I5', 'ctx': {'error': ValueError('Invalid expiry date format. Expected MM/YY.')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_payment_confirmed',), 'msg': 'Value error, Invalid date format: UZGSD0AEBT', 'input': 'UZGSD0AEBT', 'ctx': {'error': ValueError('Invalid date format: UZGSD0AEBT')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:51,366 - ERROR - Failed to retrieve data for store number 451: 500 Server Error: Internal Server Error for url: https://aqj7u5id95.execute-api.eu-west-1.amazonaws.com/prod/store_details/451
2024-09-07 10:46:51,384 - ERROR - Validation error at index 63: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': '1ZVU03X2P6', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: ZCXWWKF45G', 'input': 'ZCXWWKF45G', 'ctx': {'error': ValueError('Invalid date format: ZCXWWKF45G')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': '1CJ5OAU4BR', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'YELVM536YT', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,409 - ERROR - Validation error at index 172: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'Q1TJY8H1ZH', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: 7AHXLXIUEF', 'input': '7AHXLXIUEF', 'ctx': {'error': ValueError('Invalid date format: 7AHXLXIUEF')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': '3ZR3F89D97', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'FP8DLXQVGH', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,418 - ERROR - Validation error at index 217: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('staff_numbers',), 'msg': 'Value error, Invalid staff number: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid staff number: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,421 - ERROR - Validation error at index 231: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': '2YBZ1440V6', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: 0OLAK2I6NS', 'input': '0OLAK2I6NS', 'ctx': {'error': ValueError('Invalid date format: 0OLAK2I6NS')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'L13EQEQODP', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'HMHIFNLOBN', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,443 - ERROR - Validation error at index 333: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'O7NF1FZ74Y', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: A3PMVM800J', 'input': 'A3PMVM800J', 'ctx': {'error': ValueError('Invalid date format: A3PMVM800J')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'J3BPB68Z1J', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'F3AO8V2LHU', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,453 - ERROR - Validation error at index 381: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'SKO4NMRNNF', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: GMMB02LA9V', 'input': 'GMMB02LA9V', 'ctx': {'error': ValueError('Invalid date format: GMMB02LA9V')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'AJHOMDOHZ4', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'OH20I92LX3', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,458 - ERROR - Validation error at index 405: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('staff_numbers',), 'msg': 'Value error, Invalid staff number: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid staff number: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,460 - ERROR - Validation error at index 414: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'ID819KG3X5', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: 13PIY8GD1H', 'input': '13PIY8GD1H', 'ctx': {'error': ValueError('Invalid date format: 13PIY8GD1H')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'AE7EEW4HSS', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'OYVW925ZL8', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,465 - ERROR - Validation error at index 437: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('staff_numbers',), 'msg': 'Value error, Invalid staff number: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid staff number: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: NULL', 'input': 'NULL', 'ctx': {'error': ValueError('Invalid date format: NULL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'NULL', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'NULL', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:51,468 - ERROR - Validation error at index 447: [{'type': 'float_parsing', 'loc': ('longitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'K8CXLZDP07', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'value_error', 'loc': ('opening_date',), 'msg': 'Value error, Invalid date format: 36IIMAQD58', 'input': '36IIMAQD58', 'ctx': {'error': ValueError('Invalid date format: 36IIMAQD58')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'float_parsing', 'loc': ('latitude',), 'msg': 'Input should be a valid number, unable to parse string as a number', 'input': 'JZP8MIJTPZ', 'url': 'https://errors.pydantic.dev/2.8/v/float_parsing'}, {'type': 'string_too_long', 'loc': ('country_code',), 'msg': 'String should have at most 2 characters', 'input': 'B3EH2ZGQAV', 'ctx': {'max_length': 2}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_long'}]
2024-09-07 10:46:52,049 - ERROR - Validation error at index 266: [{'type': 'string_type', 'loc': ('product_name',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_price',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('weight',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('category',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('EAN',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('date_added',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('uuid',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('removed',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_code',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}]
2024-09-07 10:46:52,138 - ERROR - Validation error at index 751: [{'type': 'value_error', 'loc': ('product_price',), 'msg': 'Value error, Invalid product price format', 'input': 'XCD69KUI0K', 'ctx': {'error': ValueError('Invalid product price format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('EAN',), 'msg': 'Value error, EAN should only contain digits', 'input': 'OO7KH8P79I', 'ctx': {'error': ValueError('EAN should only contain digits')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_added',), 'msg': 'Value error, Invalid date format: CCAVRB79VV', 'input': 'CCAVRB79VV', 'ctx': {'error': ValueError('Invalid date format: CCAVRB79VV')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('uuid',), 'msg': 'Value error, Invalid UUID format', 'input': '7QB0Z9EW1G', 'ctx': {'error': ValueError('Invalid UUID format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('removed',), 'msg': "Value error, Removed status should be 'Still_avaliable' or 'Removed'", 'input': 'T3QRRH7SRP', 'ctx': {'error': ValueError("Removed status should be 'Still_avaliable' or 'Removed'")}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:52,145 - ERROR - Validation error at index 788: [{'type': 'string_type', 'loc': ('product_name',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_price',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('weight',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('category',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('EAN',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('date_added',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('uuid',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('removed',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_code',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}]
2024-09-07 10:46:52,146 - ERROR - Validation error at index 794: [{'type': 'string_type', 'loc': ('product_name',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_price',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('weight',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('category',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('EAN',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('date_added',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('uuid',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('removed',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_code',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}]
2024-09-07 10:46:52,209 - ERROR - Validation error at index 1133: [{'type': 'value_error', 'loc': ('product_price',), 'msg': 'Value error, Invalid product price format', 'input': 'N9D2BZQX63', 'ctx': {'error': ValueError('Invalid product price format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('EAN',), 'msg': 'Value error, EAN should only contain digits', 'input': 'E8EOGWOY8S', 'ctx': {'error': ValueError('EAN should only contain digits')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_added',), 'msg': 'Value error, Invalid date format: 09KREHTMWL', 'input': '09KREHTMWL', 'ctx': {'error': ValueError('Invalid date format: 09KREHTMWL')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('uuid',), 'msg': 'Value error, Invalid UUID format', 'input': 'CP8XYQVGGU', 'ctx': {'error': ValueError('Invalid UUID format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('removed',), 'msg': "Value error, Removed status should be 'Still_avaliable' or 'Removed'", 'input': 'BPSADIOQOK', 'ctx': {'error': ValueError("Removed status should be 'Still_avaliable' or 'Removed'")}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:52,257 - ERROR - Validation error at index 1400: [{'type': 'value_error', 'loc': ('product_price',), 'msg': 'Value error, Invalid product price format', 'input': 'ODPMASE7V7', 'ctx': {'error': ValueError('Invalid product price format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('weight',), 'msg': 'Value error, Weight must be in kg or g', 'input': 'MX180RYSHX', 'ctx': {'error': ValueError('Weight must be in kg or g')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('EAN',), 'msg': 'Value error, EAN should only contain digits', 'input': 'BHPF2JTNKQ', 'ctx': {'error': ValueError('EAN should only contain digits')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('date_added',), 'msg': 'Value error, Invalid date format: PEPWA0NCVH', 'input': 'PEPWA0NCVH', 'ctx': {'error': ValueError('Invalid date format: PEPWA0NCVH')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('uuid',), 'msg': 'Value error, Invalid UUID format', 'input': 'VIBLHHVPMN', 'ctx': {'error': ValueError('Invalid UUID format')}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}, {'type': 'value_error', 'loc': ('removed',), 'msg': "Value error, Removed status should be 'Still_avaliable' or 'Removed'", 'input': 'H5N71TV8AY', 'ctx': {'error': ValueError("Removed status should be 'Still_avaliable' or 'Removed'")}, 'url': 'https://errors.pydantic.dev/2.8/v/value_error'}]
2024-09-07 10:46:52,304 - ERROR - Validation error at index 1660: [{'type': 'string_type', 'loc': ('product_name',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_price',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('weight',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('category',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('EAN',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('date_added',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('uuid',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('removed',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}, {'type': 'string_type', 'loc': ('product_code',), 'msg': 'Input should be a valid string', 'input': nan, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}]
2024-09-10 03:56:14,617 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-13 17:53:03,143 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-15 07:08:57,368 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-15 07:16:23,044 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-15 07:25:50,456 - ERROR - Failed to create database engine: (psycopg2.OperationalError) could not translate host name "data-handling-project-readonly.cq2e8zno855e.eu-west-1.rds.amazonaws.com" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-09-15 07:36:13,124 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-15 07:39:24,240 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-15 07:40:21,942 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-15 07:50:12,965 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-15 19:40:08,351 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 00:34:06,414 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 00:42:31,352 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 00:45:30,032 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 00:52:40,899 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 00:53:54,878 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 00:59:19,205 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:00:11,635 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:02:57,225 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:05:13,330 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:06:32,229 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:30:16,629 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:32:33,342 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:33:27,270 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:33:47,547 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:35:19,589 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:37:42,379 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:43:57,529 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 01:45:29,297 - ERROR - Failed to extract data from S3: initial_value must be str or None, not MagicMock
2024-09-16 02:01:39,207 - ERROR - Failed to extract data from S3: a bytes-like object is required, not 'MagicMock'
2024-09-16 02:02:38,270 - ERROR - Failed to extract data from S3: a bytes-like object is required, not 'MagicMock'
2024-09-16 02:03:42,435 - ERROR - Failed to extract data from S3: a bytes-like object is required, not 'MagicMock'
2024-09-16 02:04:16,957 - ERROR - Failed to extract data from S3: a bytes-like object is required, not 'MagicMock'
2024-09-16 02:06:53,882 - ERROR - Failed to extract data from S3: a bytes-like object is required, not 'MagicMock'
2024-09-16 02:08:37,510 - ERROR - Failed to extract data from S3: a bytes-like object is required, not 'MagicMock'
2024-09-16 02:14:23,593 - ERROR - Failed to extract data from S3: a bytes-like object is required, not 'MagicMock'
2024-09-16 02:18:59,728 - ERROR - Failed to extract data from S3: a bytes-like object is required, not 'MagicMock'
